import CertKernel
import Std.Data.HashMap

/-!
# A machine-speed evaluator for the all-even `Q_i` certificate

Same certificate as `FltVandiver.QiCert.vandiverCert`, evaluated as
`Q_i^k = h^(S_i - N d_i)` with `h = t^k` of order `p`, where
`S_i = Σ_b c_b b^(p-1-i)` and `c_b = dlog_h((h^b - 1)^k)`.  The powers `b^(p-1-i)` mod `p`
come from a primitive-root table, so each index costs one pass over `b`
with no exponentiation.  Every table fact the bridge needs is re-verified by
an explicit check inside the certificate, so the proof never reasons about
how the tables were built.
-/

namespace FltVandiver.QiCert.Fast2

open CertKernel

/-- Distinct prime factors of `n` by trial division. -/
def primeFactors (n : Nat) : List Nat := Id.run do
  let mut m := n
  let mut fs : List Nat := []
  let mut q := 2
  while q * q ≤ m do
    if m % q == 0 then
      fs := q :: fs
      while m % q == 0 do
        m := m / q
    q := q + 1
  if m > 1 then fs := m :: fs
  return fs

def isPrimRoot (g p : Nat) (fs : List Nat) : Bool :=
  fs.all (fun q => powModK g p ((p - 1) / q) != 1)

/-- A primitive root mod `p` (proof-irrelevant: its table is verified). -/
def findPrimRoot (p : Nat) : Nat := Id.run do
  let fs := primeFactors (p - 1)
  let mut g := 2
  while g < p && !isPrimRoot g p fs do
    g := g + 1
  return g

/-- `[g^0 % m, …, g^(n-1) % m]`. -/
def powTable (g m n : Nat) : Array Nat := Id.run do
  let mut arr : Array Nat := Array.mkEmpty n
  let mut cur := 1 % m
  for _ in [0:n] do
    arr := arr.push cur
    cur := cur * g % m
  return arr

/-- `ind[x] = j` when `gpow[j] = x`. -/
def indTable (gpow : Array Nat) (p : Nat) : Array Nat := Id.run do
  let mut ind : Array Nat := Array.replicate p 0
  for j in [0:gpow.size] do
    ind := ind.set! (gpow.getD j 0) j
  return ind

/-- Discrete-log map of the order-`p` subgroup generated by `h` mod `ℓ`. -/
def dlogMap (h ℓ p : Nat) : Std.HashMap Nat Nat := Id.run do
  let mut m : Std.HashMap Nat Nat := {}
  let mut cur := 1 % ℓ
  for j in [0:p] do
    m := m.insert cur j
    cur := cur * h % ℓ
  return m

/-- `c[b] = dlog_h((h^b − 1)^k)` for `b = 1..half` (`c[0] = 0`). -/
def cTable (h ℓ k half : Nat) (dl : Std.HashMap Nat Nat) : Array Nat := Id.run do
  let mut arr : Array Nat := Array.mkEmpty (half + 1)
  arr := arr.push 0
  for b in [1:half+1] do
    let x := powModK ((powModK h ℓ b + (ℓ - 1)) % ℓ) ℓ k
    arr := arr.push (dl.getD x 0)
  return arr

/-- `(acc + Σ_{b=1}^{n} f b) % p`, accumulated in a tail loop. -/
def sumMod (f : Nat → Nat) (p : Nat) : Nat → Nat → Nat
  | 0, acc => acc % p
  | n + 1, acc => sumMod f p n ((acc + f (n + 1)) % p)

/-- The test at one even index `i`: `S_i ≢ N·d_i (mod p)`. -/
def checkIndex (p pm1 half N : Nat) (c gpow ind : Array Nat) (i : Nat) : Bool :=
  let e := p - 1 - i
  let w : Nat → Nat := fun b => gpow.getD ((e * ind.getD b 0) % pm1) 0
  let S := sumMod (fun b => c.getD b 0 * w b) p half 0
  let D := sumMod (fun b => b * w b) p half 0
  S % p != (N * D) % p

/-- The certificate. Structural checks, table verifications, then the per-index test. -/
def fast2Cert (p ℓ t : Nat) (irr : List Nat) : Bool :=
  let k := (ℓ - 1) / p
  let half := (p - 1) / 2
  let N := k / 2
  let h := powModK t ℓ k
  let g := findPrimRoot p
  let gpow := powTable g p (p - 1)
  let ind := indTable gpow p
  let dl := dlogMap h ℓ p
  let c := cTable h ℓ k half dl
  (ℓ % p == 1) && (h != 1) && (powModK t ℓ (ℓ - 1) == 1) && (k % 2 == 0) &&
  (0 < g && g < p) &&
  (gpow.getD 0 0 == 1 % p) &&
  (List.range (p - 2)).all (fun j => gpow.getD (j + 1) 0 == gpow.getD j 0 * g % p) &&
  (List.range (p - 1)).all (fun b0 =>
    let b := b0 + 1
    (ind.getD b 0 < p - 1) && (gpow.getD (ind.getD b 0) 0 == b)) &&
  (List.range half).all (fun b0 =>
    let b := b0 + 1
    powModK h ℓ (c.getD b 0) == powModK ((powModK h ℓ b + (ℓ - 1)) % ℓ) ℓ k) &&
  irr.all (fun i => (i + 3 ≤ p) && checkIndex p (p - 1) half N c gpow ind i)

end FltVandiver.QiCert.Fast2
